src/main/java/edu/caltech/ssel/recruiting/model/Experiment.java
/*
 * Copyright (C) 1998-2009, <a href="http://www.ssel.caltech.edu">SSEL</a>,
 * at Caltech, Pasadena, CA 91125.
 *
 * MooreRecruiting is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 * USA.
 *
 */

package edu.caltech.ssel.recruiting.model;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.persistence.*;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import org.appfuse.model.BaseObject;
import org.appfuse.model.User;

/**
* @author Michael Kolodrubetz, SSEL, Caltech
* @author <a href="mailto:wmyuan@hss.caltech.edu">Walter M. Yuan</a>, SSEL, Caltech
*/
@Entity
@Table(name="experiment")
public class Experiment extends BaseObject {
    
    /*
     * FULL = 0
     * CLOSED = 1
     * OPEN = 2
     * FINISHED = 3
     * CANCELLED = 4
     * IMPORTED = 5
     */
    public static enum Status {
        FULL, CLOSED, OPEN, FINISHED, CANCELLED, IMPORTED;
        
        public String toString() {
            switch(this) {
                case FULL:
                    return "Full";
                case CLOSED:
                    return "Closed";
                case OPEN:
                    return "Open";
                case FINISHED:
                    return "Finished";
                case CANCELLED:
                    return "Cancelled";
                case IMPORTED:
                    return "Imported";
                default:
                    return null;
            }
        }
        
        public String getName() {
            return this.name();
        }
        
        public String getString() {
            return this.toString();
        }
    };
    
    private Long id;
    private Experimenter runby;
    private Experimenter principle;
    private User reservedBy;
    private Date expDate;
    private Date startTime;
    private int setupBuffer;
    private Date endTime;
    private int cleanupBuffer;
    private int maxNumSubjects;
    private int minNumSubjects;
    private float showUpFee;
    private String instruction;
    private float signupFreezeTime;
    private Location location;
    private ExperimentType type;
    private Status status;
    private Filter filter;
    private Survey survey;
    private boolean published=false;
    private boolean checkedIRB=false;
    private boolean payGatePayment = false;
    private boolean manualPayment = false;
    private boolean invisible=false;
    private Boolean reserveLaptops;
    
    private static final SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    
    /** Creates a new instance of Experiment */
    public Experiment() {
    }
    
    @ManyToOne
    public Experimenter getRunby() {
        return runby;
    }
    
    public void setRunby(Experimenter runby) {
        this.runby = runby;
    }
    
    @ManyToOne
    public Experimenter getPrinciple() {
        return principle;
    }
    
    public void setPrinciple(Experimenter principle) {
        this.principle = principle;
    }
    
    @ManyToOne
    public User getReservedBy() {
        return reservedBy;
    }
    
    public void setReservedBy(User reservedBy) {
        this.reservedBy = reservedBy;
    }
    
    @Temporal(TemporalType.DATE)
    public Date getExpDate() {
        return expDate;
    }
    
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }
    
    @Temporal(TemporalType.TIME)
    public Date getStartTime() {
        return startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    
    @Temporal(TemporalType.TIME)
    public Date getEndTime() {
        return endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    //Get the actual time and date when the experiment signup is frozen
    @Transient
    public GregorianCalendar getFreezeTime() {

        // BRS 2012-04-04
        if (expDate == null || startTime == null) {
            // Can't calculate the freezeTime
            return null;
        }

        //Set "start" to be the absolute start time of the experiment
        GregorianCalendar start = new GregorianCalendar(expDate.getYear()+1900, expDate.getMonth(), expDate.getDate(), startTime.getHours(), startTime.getMinutes());
        //And then subtract the signup freeze time
        start.add(Calendar.MINUTE, -Math.round(signupFreezeTime));
        
        return start;
    }

    // BRS 2011-10-27
    @Transient
    public GregorianCalendar getStartDateTime() {
        GregorianCalendar start = new GregorianCalendar(expDate.getYear()+1900, expDate.getMonth(), expDate.getDate(), startTime.getHours(), startTime.getMinutes());
        return start;
    }
    
    public int getMaxNumSubjects() {
        return maxNumSubjects;
    }
    
    public void setMaxNumSubjects(int maxNumSubjects) {
        this.maxNumSubjects = maxNumSubjects;
    }
    
    public int getMinNumSubjects() {
        return minNumSubjects;
    }
    
    public void setMinNumSubjects(int minNumSubjects) {
        this.minNumSubjects = minNumSubjects;
    }
    
    public float getShowUpFee() {
        return showUpFee;
    }
    
    public void setShowUpFee(float showUpFee) {
        this.showUpFee = showUpFee;
    }
    
    @Column(columnDefinition="MEDIUMTEXT NULL")
    public String getInstruction() {
        return instruction;
    }
    
    public void setInstruction(String instruction) {
        this.instruction = instruction;
    }
    
    public float getSignupFreezeTime() {
        return signupFreezeTime;
    }
    
    public void setSignupFreezeTime(float signupFreezeTime) {
        this.signupFreezeTime = signupFreezeTime;
    }
    
    @ManyToOne
    public Location getLocation() {
        return location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    
    @ManyToOne
    public ExperimentType getType() {
        return type;
    }
    
    public void setType(ExperimentType type) {
        this.type = type;
    }
    
    public Status getStatus() {
        return status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    
    @Transient
    public String getStatusString() {
        return status.toString();
    }
    
    public void setStatusString(String s) {
        try {
            status = Status.valueOf(s);
        } catch (Exception e) {
            System.err.println("Failed to set experiment status: " + s + " is not a valid status");
        }
    }
    
    @ManyToOne
    public Filter getFilter() {
        return filter;
    }
    
    public void setFilter(Filter filter) {
        this.filter = filter;
    }
    
    @Id @GeneratedValue(strategy=GenerationType.AUTO)
    public Long getId() {
        return id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @ManyToOne
    public Survey getSurvey() {
        return survey;
    }
    
    public void setSurvey(Survey survey) {
        this.survey = survey;
    }

    @Column(name="published")
    public boolean getPublished() {
        return published;
    }

    public void setPublished(boolean published) {
        this.published = published;
    }
    
    @Transient
    public String getFormattedDescription() {
        StringBuffer buf = new StringBuffer();
        try {
            buf.append(id)
               .append(") ")
               .append(formatter.format(expDate))
               .append("; ")
               .append(location.getName());
            if(instruction != null && instruction.length() > 0) {
                buf.append("; ")
                   .append(instruction);
            }
        } catch(Exception any) {
            buf = new StringBuffer();
            buf.append(id);
        }
        
        if(buf.length() > 40)
            return buf.toString().substring(0, 36) + "...";
        else
            return buf.toString();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
            .append(runby).append(principle).append(reservedBy).append(expDate)
            .append(startTime).append(endTime).append(maxNumSubjects)
            .append(setupBuffer).append(cleanupBuffer)
            .append(minNumSubjects).append(showUpFee).append(instruction)
            .append(signupFreezeTime).append(location).append(type).append(status)
            .append(filter).append(survey).append(published).append(checkedIRB).append(invisible).toHashCode();
    }

    @Override
    public boolean equals(final Object other) {
        if (this == other)
            return true;
        if (!(other instanceof Experiment))
            return false;
        Experiment castOther = (Experiment) other;

src/main/java/edu/caltech/ssel/recruiting/model/Question.java
/*
 * Copyright (C) 1998-2009, <a href="http://www.ssel.caltech.edu">SSEL</a>,
 * at Caltech, Pasadena, CA 91125.
 *
 * MooreRecruiting is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 * USA.
 *
 */


package edu.caltech.ssel.recruiting.model;

import java.util.List;
import javax.persistence.*;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import org.appfuse.model.BaseObject;
import com.thoughtworks.xstream.XStream;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
* @author Michael Kolodrubetz, SSEL, Caltech
* @author <a href="mailto:wmyuan@hss.caltech.edu">Walter M. Yuan</a>, SSEL, Caltech
*/
@Entity
@Table(name="question")
public class Question extends BaseObject implements Cloneable {
    
    Log log = LogFactory.getLog(Question.class);
    
    public static enum QStyle {
        CHECK_BOX, RADIO, DROP_LIST;
        
        public String toString() {
            switch(this) {
                case CHECK_BOX:
                    return "Checkbox";
                case RADIO:
                    return "Radio button";
                case DROP_LIST:
                    return "Drop-down list";
                default:
                    return null;
                    
            }
        }
        
        //Required for accessing proper name (rather than toString()) from jsp pages
        public String getName() {
            return this.name();
        }
    };
    
    private Long id;
    private String label;
    private String question;
    private QStyle style;
    private String options;
    
    /** Creates a new instance of Question */
    public Question() {
    }
    
    @Transient
    public String getStyleString() {
        switch(style) {
            case CHECK_BOX:
                return "CHECK_BOX";
            case RADIO:
                return "RADIO";
            case DROP_LIST:
                return "DROP_LIST";
            default:
                return null;
        }
    }
    
    @Id @GeneratedValue(strategy=GenerationType.AUTO)
    public Long getId() {
        return id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(unique=true)
    public String getLabel() {
        return label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    
    public String getQuestion() {
        return question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    
    public QStyle getStyle() {
        return style;
    }
    
    public void setStyle(QStyle style) {
        this.style = style;
    }
    
    /*@CollectionOfElements //Cannot set fetch type to eager, or it gives error: "cannot simultaneously fetch multiple bags"
    public List<String> getOptions() {
        return options;
    }
    
    public void setOptions(List<String> options) {
        this.options = options;
    }*/
    
    @Column(columnDefinition="MEDIUMTEXT NULL")
    public String getOptions() {
        return options;
    }
    
    public void setOptions(String s) {
        options = s;
    }

    @Transient
    public List<String> getOptionList() {
        XStream xstream = new XStream();
        xstream.alias("list", List.class);
        return (List<String>) xstream.fromXML(options);
    }
    
    public void setOptionList(List<String> lst) {
        XStream xstream = new XStream();
        xstream.alias("list", List.class);
        options = xstream.toXML(lst);
    }

    public String getNameOf(QStyle t) {
        switch(t) {
            case CHECK_BOX:
                return "Checkbox";
            case RADIO:
                return "Radio button";
            case DROP_LIST:
                return "Drop-down list";
        }
        return null;//Should never reach this point
    }
    
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
        .append("id", id.toString())
        .append("label", label)
        .append("question", question)
        .append("options", options)
        .append("type", getNameOf(style)).toString();
    }
    
    public boolean equals(Object object) {
        if(this==object)
            return true;
        if(!(object instanceof Question))
            return false;
        
        Question q = (Question)object;
        
        //Check equality by "unique" fields (not id, in case of null id)
        return StringUtils.equals(q.getLabel(), this.getLabel());
    }
    
    public int hashCode() {
        return (int)(id % Integer.MAX_VALUE);
    }
    
    public Question clone() {
        Question q = new Question();
        q.id = this.id;
        q.label = this.label;
        q.question = this.question;
        q.style = this.style;
        q.options = this.options;
        return q;
    }
    
}

src/main/java/edu/caltech/ssel/recruiting/webapp/controller/AdministratorController.java
/*
 * Copyright (C) 1998-2009, <a href="http://www.ssel.caltech.edu">SSEL</a>,
 * at Caltech, Pasadena, CA 91125. 
 *
 * MooreRecruiting is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 * USA.
 *
 */

package edu.caltech.ssel.recruiting.webapp.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

/**
* @author Michael Kolodrubetz, SSEL, Caltech
* @author <a href="mailto:wmyuan@hss.caltech.edu">Walter M. Yuan</a>, SSEL, Caltech
*/
public class AdministratorController implements Controller {
    
    /** Creates a new instance of AdministratorController */
    public AdministratorController() {
    }

    public ModelAndView handleRequest(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse) throws Exception {
        return new ModelAndView();
    }
    
}

src/main/webapp/WEB-INF/pages/dataAccessFailure.jsp
<%@ include file="/common/taglibs.jsp" %>

<title>Data Access Error</title>
<head>
    <meta name="heading" content="Data Access Failure"/>
    <meta name="menu" content="AdminMenu"/>
</head>

<p>
    <c:out value="${requestScope.exception.message}"/>
</p>

<!--
<% 
Exception ex = (Exception) request.getAttribute("exception");
ex.printStackTrace(new java.io.PrintWriter(out)); 
%>
-->

<a href="calendar.html" onclick="history.back();return false">&#171; Back</a>

src/main/webapp/WEB-INF/pages/experimenter.jsp
<%@ include file="/common/taglibs.jsp"%> 

<head>
    <title><fmt:message key="experimenter.title"/></title>
    <meta name="heading" content="<fmt:message key='experimenter.heading'/>"/>
    <meta name="menu" content="ExperimenterMenu"/>
    
    <script type="text/javascript" src="<c:url value='/scripts/common.js'/>"></script>
    <script type="text/javascript">
        
function setupExp() {
    var selObj = $("myExperimentSelect");
    var optAry = selObj.options;
    var idx = selObj.selectedIndex;
    if(optAry[idx].value != "new" && optAry[idx].value != "") {
        document.location.href = "modifyexperiment.html?id="+optAry[idx].value;
    } else {
        alert("<fmt:message key="experiment.select.invalid"/>");
    }
}
    </script>
</head>

<h2>Experiment Type Management</h2>
<ul class="glassList">
    <li><a href="experimenttype.html">View/Edit Existing Types</a></li>
    <li><a href="experimenttypeform.html">Add New Type</a></li>
</ul>

<h2>Experiment Management</h2>
<ul class="glassList">
    <li><a href="clearsession.html?view=experiment">Create New Experiment</a></li>
    <li><a href="calendar.html">Select From Calendar</a>&nbsp;<i>OR</i>&nbsp;
        <select name="myExperiment" id="myExperimentSelect">
            <option value="new"><fmt:message key="experiment.select.choose"/></option>
            <c:forEach items="${expList}" var="expItem">
                <c:if test="${expItem.status.name != 'FINISHED'}">
                    <option value="${expItem.id}"><c:out value="${expItem.formattedDescription}"/></option>
                </c:if>
            </c:forEach>
        </select>
        &nbsp;<input type="button" onclick="setupExp()" value="<fmt:message key='button.view'/>">
    </li>
</ul>

<h2>Personal Settings</h2>
<ul class="glassList">
    <li><a href="userform.html">Edit My Profile</a></li>
</ul>

src/main/webapp/WEB-INF/pages/filterform.jsp
<%@ include file="/common/taglibs.jsp"%> 
<%@ taglib prefix="mylib" uri="/WEB-INF/mylib.tld" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<head>
    <title><fmt:message key="filterForm.title"/></title>
    <meta name="heading" content="<fmt:message key='filterForm.heading'/>"/>
    <meta name="menu" content="ExperimenterMenu"/>
    
    <link rel="stylesheet" type="text/css" href="/styles/filterform.css" />
    <link rel="stylesheet" type="text/css" href="/styles/common.css" />
    <link rel="stylesheet" type="text/css" href="/styles/tripick.css" />

    <script type="text/javascript">
        var useFilter_orig = "<c:out value='${useFilter}'/>";
        var conditions = <c:out value='${conditionsJSON}' escapeXml="false" />;
    </script>
    <script type='text/javascript' src='<c:url value="/dwr/engine.js"/>'></script>
    <script type='text/javascript' src='<c:url value="/dwr/interface/conditionManagerDWR.js"/>'></script>
    <script type='text/javascript' src='<c:url value="/dwr/interface/experimentManagerDWR.js"/>'></script>
    <script type="text/javascript" src="<c:url value='/scripts/jquery.js'/>"></script>
    <script type="text/javascript" src="<c:url value='/scripts/filterform.js'/>"></script>

    <style type="text/css">
        .offset_title
        {
        color: #3300e0;
        }
        #filterOptionsButtons {
            margin: 1em;
        }
        #filterOptionsButtons input {
            margin-right: 1em;
        }
        fieldset {
            margin-bottom: 1em;
        }
        div#main form ul {
            border-top: 1px solid silver;
        }
        div#main form ul li {
            border-bottom: 1px solid silver;
            border-collapse: collapse;
            padding-bottom: 5px;
        }
        a.disabled {
            color: gray;
        }
        .disabled {
            color: gray;
        }
        #filterOptions {
            position: relative; /* enable absolute positioning of "Filter ID" */
        }
        #filterID {
            font-style: italic;
            text-align: right;
            position: absolute;
            right: 10px;
            bottom: 5px;
        }
        #conditionFieldset {
            display: none;
            border: 1px solid silver;
            line-height: 2em;
        }
        #conditionSubforms {
            display: none;
        }
        .editedCondition {
            background-color: #E5C9BE;
        }
        .conditionIdLabel {
            font-style: italic;
            text-align: right;
            display: block !important;
            padding-bottom: 0;
            marginp-bottom: 0;
        }
        #bottomPadding {
            height: 300px;
        }

    </style>
    
</head>


<%@ include file="/common/progressDiv.jsp"%>

<form:form id="filterForm" commandName="filter" name="filterForm" action="filterform.html">
    <form:errors path="name" cssClass="fieldError"/> 

    <input type="checkbox" name="checkedIRB" id="checkedIRB" />&nbsp;<appfuse:label key="filter.checkedIRB"/>  <br/> <br/>

    <fieldset id="filterOptions">
        <legend>Filter Options</legend>
        <input type="radio" id="doNotUseFilter" name="useFilter" value="none" <c:if test="${useFilter=='none'}">checked="checked"</c:if> /> Do not use filter <br/>
        <input type="radio" name="useFilter" value="default" <c:if test="${useFilter=='default'}">checked="checked"</c:if> /> Use default filter for this experiment type <br/>
        <input type="radio" name="useFilter" value="separate" <c:if test="${useFilter=='separate'}">checked="checked"</c:if> /> Use separate filter for this experiment <br/>
        <div id="filterOptionsButtons" style="display: none">
            <input type="submit" id="optCancel" value="Cancel"/>
        </div>
        <div id="filterID">Filter ID: <c:out value="${filter.id}"/></div>
    </fieldset>

    <c:if test="${useFilter!='none'}">
        <fieldset id="filterConditions">
            <legend>Filter Conditions</legend>
            <c:if test="${useFilter=='default'}">
                <b>Note: Any changes will affect all other experiments using the default filter for this experiment type.</b>
            </c:if>
            <c:choose>
                <c:when test="${empty filter.conditions}">
                    <p> The filter has no conditions.  </p>
                </c:when>
                <c:otherwise>
                    <ul id="conditionList">
                        <c:forEach var="cond" items="${filter.conditions}" varStatus="status">
                            <li>
                            <a href="#" conditionId="<c:out value='${cond.id}'/>" conditionIndex="<c:out value='${status.index}'/>" class="editLink">Edit</a> | 
                            <a href="#" conditionId="<c:out value='${cond.id}'/>" class="deleteLink">Delete</a>
                            &mdash; <c:out value="${cond.humanString}"/>
                            <div class="conditionIdLabel"> Condition ID: <c:out value="${cond.id}"/> </div>
                            </li>
                        </c:forEach>
                    </ul>
                </c:otherwise>
            </c:choose>
            <div id="addConditionContainer">
                Add new condition &mdash;
                <select id="addCondition">
                    <option disabled selected value="">Select condition type</option>
                    <c:forEach var="conditionType" items="${conditionTypes}">
                        <option value='<c:out value="${conditionType[0]}"/>'><c:out value="${conditionType[1]}"/></option>
                    </c:forEach>
                </select>
            </div>

            <fieldset id="conditionFieldset">
                <legend>Add/Edit Condition</legend>
                <input type="hidden" name="conditionId" value=""/>
                <input type="hidden" name="conditionType" value=""/>
                <br/>
                <input type="submit" name="saveCondition" id="saveCondition" value="Save" />
                <button type="button" id="cancelConditionEdit">Cancel</button>
            </fieldset>

        </fieldset>
    </c:if>

    <p>
        Eligible subjects: <span id="eligibleCount">Counting...</span> &nbsp;&nbsp;&nbsp;&nbsp;
        <br/>
        <em>Note: Question Result Conditions and Experiment Conditions for future experiments are ignored when counting eligible subjects.</em>
    </p>

    <input type="checkbox" name="checkedIRB_bottom" id="checkedIRB_bottom" />&nbsp;<appfuse:label key="filter.checkedIRB"/>  <br/> <br/>

    <div id="buttons" class="buttonBar bottom">
        <input type="submit" class="button" name="back" value="<fmt:message key='button.back'/>" onclick="bCancel=true"/>
        <input type="submit" class="button" name="next" value="<fmt:message key='button.next'/>" onclick="bCancel=false"/>
        <input type="submit" class="button" name="cancel" value="<fmt:message key='button.cancel'/>" onclick="bCancel=true"/> 
        &nbsp;<i>or</i>&nbsp;<input type="submit" class="button" name="savenow" value="<fmt:message key='button.saveNow'/>" onclick="bCancel=false"/> 
    </div>
</form:form>

<%--
This div is immediately detached from the DOM by filterform.js,
and the individual subforms are re-attached as needed within #conditionFieldset.
--%>
<div id="conditionSubforms">

    <div conditionType="ExperimentTypeCondition">
        <select name="onList">
            <option selected value="false">Exclude</option>
            <option value="true">Include only</option>
        </select>
        <div>subjects who have</div>
        <select name="history">
            <option selected value="true">participated in experiments</option>
            <option value="false">signed up for future experiments</option>
        </select>
        <div>of the following type(s):</div>
        <div id="experimentTypeList"> </div>
        <select id="addExperimentType">
            <option disabled selected value="">Add experiment type</option>
            <c:forEach var="experimentType" items="${experimentTypes}">
                <option value='<c:out value="${experimentType.id}"/>'><c:out value="${experimentType.name}"/></option>
            </c:forEach>
        </select>
    </div>

    <div conditionType="ExperimentCondition">
        <select name="onList">
            <option selected value="false">Exclude</option>
            <option value="true">Include only</option>
        </select>
        <div>subjects who have signed up for (in the case of a future experiment) or participated in (in the case of a past experiment) the following experiment:</div>
        <select id="experimentCondition_type">
            <option disabled selected value="">Select experiment type</option>
            <c:forEach var="experimentType" items="${experimentTypes}">
                <option value='<c:out value="${experimentType.id}"/>'><c:out value="${experimentType.name}"/></option>
            </c:forEach>
        </select>
        <select id="experimentCondition_experiment" name="experiment">
            <option disabled selected value="">Select experiment</option>
        </select>
        <span id="#experimentCondition_loading"></span>
    </div>

    <div conditionType="NoShowCondition">
        Exclude subjects with more than
        <input type="text" name="maxNoShows" size="2" />
        no-shows.
    </div>

    <div conditionType="PoolCondition">
        <select name="memberOf">
            <option selected value="true">Include only</option>
            <option value="false">Exclude</option>
        </select>
        <div>subjects who are members of the following subject pool(s):</div>
        <div id="subjectPoolList"> </div>
        <select id="addSubjectPool">
            <option disabled selected value="">Add subject pool</option>
            <c:forEach var="subjectPool" items="${subjectPools}">
                <option value='<c:out value="${subjectPool.id}"/>'><c:out value="${subjectPool.name}"/></option>
            </c:forEach>
        </select>
    </div>

    <div conditionType="QuestionResultCondition">
        <div>
            Include only subjects who
            <select name="filterType">
                <option value="CHECK_ALL">check all</option>
                <option value="CHECK_SOME">check some</option>
                <option value="CHECK_NONE">check none</option>
                <option value="CHECK_NOT_SOME">do not check all</option>
                <option value="SELECT">select one</option>
                <option value="NO_SELECT">select none</option>
            </select>
            of the following checked options for question
            <select name="question">
                <option disabled selected value="">Select question</option>
                <c:forEach var="q" items="${questions}">
                    <option value='<c:out value="${q.id}"/>'><c:out value="${q.label}"/></option>
                </c:forEach>
            </select>
        </div>
        <div id="questionOptionsContainer">
            <c:forEach var="q" items="${questions}">
                <div questionId='<c:out value="${q.id}"/>' style="display: none">
                    <c:forEach var="option" varStatus="status" items="${q.optionList}">
                        <input type="checkbox" name="questionOptions"
                            value='<c:out value="${status.index}"/>' />
                        <c:out value="${option}"/>
                    </c:forEach>
                </div>
            </c:forEach>
        </div>
    </div>

</div>

<%--
Add extra padding to the bottom of the page so it doesn't scroll up when the condition subform is removed.
--%>
<div id="bottomPadding">
</div>